services:
  apps:
    build: ./apps
    container_name: ct-compose-apps-ahmad
    image: latdockerafara/apps-ahmad
    restart: always
    ports:
      - "5000:3000"
    volumes:
      - apps-data:/app/public/images

volumes:
  apps-data: