service:
  apps:
  build: ./apps
  container-name: ct-apps-ahmad
  image: latdockerafara/apps-ahmad
  restart: always
  port:
    - "3000:3000"
  volumes:
    - apps-data:/app/public/images

volumes:
  apps-data: